### PR TITLE
feat: add numix accent and numix preset

### LINKED ISSUE #126: Proposal for new accent colour, numix red
I've been working on a new colour *accent* for Boxy which uses the principal colour of the [Numix Project](http://satya164.github.io/numix/). The colour hex code is `#D64937` and the RGB is `[214, 73, 55]`, the colour info. page, [colorhexa.com](http://www.colorhexa.com/d64937), calls this colour 'moderate red', the *Numix Project* calls it 'Numix Red', I'd describe it as a 'reddy-brown' or a 'dirty-reddy-orange' - it is hard to categorize.

numix_red

*Numix Red* is already used as the principal colour of 4 Sublime Text themes available on *Package Control*:

- [Numix Theme](https://packagecontrol.io/packages/Numix%20Theme) 44k installs - uses Numix Red
- [Theme - Numix](https://packagecontrol.io/packages/Theme%20-%20Numix) 37k installs - uses Numix Red
- [Theme - Numix Light](https://packagecontrol.io/packages/Theme%20-%20Numix%20Light) 9k installs - uses Numix Red
- [Theme - Brogrammer](https://packagecontrol.io/packages/Theme%20-%20Brogrammer) 94k installs - uses colours very close to Numix Red

Although I like the colour, none of these themes satisfied my design requirements and I've been using *Predawn* for the last few years before I discovered *Boxy* a few weeks ago.

Here is how *Numix Red* would fit in with the existing *Boxy* colour *accents*:

boxy_colour_chart

Here's what I've done so far:

#### Image Conversion:

I used [Imagemagick](http://www.imagemagick.org/script/index.php) to convert all the button, scrollbar, sidebar, and tab images.

This was done by taking the images from the orange accent files and using a `Bash` script to convert them using the following commands:

```
# Orange accent to Numix:
convert "$in" -type TrueColorMatte -channel RGBA -fill "#D64937" -opaque "#F2683E" png32:"$out"

# Orange accent to Numix; shadow effect for the 6 'Atomized' expanded folder images:
convert "$in" -type TrueColorMatte -channel RGBA -fill "#A93223" -opaque "#C25332" png32:"$out"
```

There are 2 issues with the colour conversion:

- Size: The total size of all the Numix images is ~143k, the other accents are all ~77k, clearly my conversion script will need to be run again with a compression setting used.
- The 6 `button_selection_atomized_on` and `button_word_atomized_on` images need fixing. The different shade/opacity used on the edge of these in the Numix version retains the orange accent colour.

#### Boxy Tomorrow.sublime-theme:

I've added Numix entries throughout the `Boxy Tomorrow.sublime-theme` file - a copy of the file is in [this gist](https://gist.github.com/mattst/c7f160b7a373e13190e58b1baab70dc9).

To do this I worked through the file, copying each `tangerine` (a good word to search for) entry or section and converting the names, colour, and paths to Numix, before pasting the new entry or section back into the file beneath the tangerine entry or section.

While doing this I discovered that 2 additional colours were needed; 1 for the `label_control` on the `status_bar` and 1 for the `tab_label`. Here are the details of those entries:

Note that I am not 100% happy with the colours that I've chosen for these and will play around with some other colours.

```
Tangerine entry:

  {
    "class": "label_control",
    "settings": ["!theme_accent_mono", "theme_statusbar_colored", "theme_accent_tangerine"],
    "parents": [{"class": "status_bar"}],
    "color": [253, 237, 231]
  },

Numix entry:

  {
    "class": "label_control",
    "settings": ["!theme_accent_mono", "theme_statusbar_colored", "theme_accent_numix"],
    "parents": [{"class": "status_bar"}],
    "color": [251, 236, 234]
  },

Tangerine entry:

  {
    "class": "tab_label",
    "settings": ["!theme_accent_mono", "theme_bar_colored", "theme_accent_tangerine"],
    "fg": [250, 213, 199]
  },

Numix entry:

  {
    "class": "tab_label",
    "settings": ["!theme_accent_mono", "theme_bar_colored", "theme_accent_numix"],
    "fg": [246, 215, 213]
  },
```

#### Prototype:

What I have at the moment is a prototype. The screen capture image below is what `Boxy Tomorrow.sublime-theme` looks like with  `"theme_accent_numix": true`. I have also done a screen capture of the same window but with `"theme_accent_orange": true` - this is so that you can see that the Numix red *accent* is very different from the orange *accent* which is the closest in colour of the existing *accent* colour schemes.

Prototype of Boxy Tomorrow with Numix red accent:

boxy_tomorrow_numix

Boxy Tomorrow with the existing orange accent for comparison:

boxy_tomorrow_orange

#### Going Forwards:

I have some questions:

- Most importantly: Would you like me to continue developing this? Clearly adding the Numix accent to `Boxy Monokai.sublime-theme`, `Boxy Ocean.sublime-theme`, and to `Boxy Yesterday.sublime-theme` will take quite a lot of work, so if you don't want the Numix accent then clearly I won't bother.

Assuming that the answer is "yes":

- Did you use *Imagemagick* to convert the button, scrollbar, sidebar, and tab images from one colour scheme to another? If so is there a better command line that I should use instead of the `convert` lines I used in the *Image Conversion* section above?

- What compression level would you like me to use when creating the `PNG` files?

- The `.src/settings/common.json` file will need a `numix` dictionary entry in the `accents` list. Am I correct in thinking that the `foreground` colour should be the same as the `tab_label` class colour in the `.sublime-theme` files and that the `highlighted` colour should be the same as the `label_control` class with the `status_bar` class `parents`? What exactly does this `accents` list control?

- Do you have any hints for choosing the `foreground` and `highlighted` colours? All I did was enter the Numix colour on [this page](http://www.w3schools.com/colors/colors_picker.asp) and I then chose colours at the lighter end of the list of the colours on the right of the page.

- Would you have any objection to my adding a Numix preset to `boxy_presets.py`?

I hope this all meets with your approval. Best wishes, mattst

### PR DESCRIPTION
**Pull request by mattst**
#### Description

Added Numix accent colour and Numix theme preset.

#### Motivation and Context

The Numix colour is lovely and looks great in Boxy. The proposal to add this accent and preset was suggested by me in the [Proposal for new accent colour, numix red](https://github.com/oivva/st-boxy/issues/126) issue and *permission* to go ahead was given by oivva.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.

#### What Was Done

On GitHub forked `oivva/st-boxy` to `mattst/st-boxy`

Cloned the forked copy to my local system

Created a new branch called `numix` from the `dev` branch (commit `f5c8f1dd3f`)

Added all numix accent image files to folder (see **Image Files** section below): `st-boxy/assets/accents/numix/`

Added `numix` dictionary to the `accents` list in: `st-boxy/.src/settings/common.json`

Ran the `npm install` command to install `gulp` and its dependencies

Ran the `gulp build:themes` command to rebuild the 4 `.sublime-theme` files. Output:

```
$ gulp build:themes

/my/path/to/Boxy Theme/st-boxy/node_modules/conventional-changelog/node_modules/conventional-changelog-core/node_modules/git-remote-origin-url/index.js:2
const gitconfig = require('gitconfiglocal');
^^^^^
[11:20:05] Using gulpfile ~/Programming/Sublime Text Plugins/Boxy Theme/st-boxy/gulpfile.js
[11:20:05] Starting 'clean:themes'...
[11:20:05] Finished 'clean:themes' after 5.5 ms
[11:20:05] Starting 'build:themes'...
[build:themes] Finished successfully
[11:20:05] Finished 'build:themes' after 322 ms
```

##### Additions to: `st-boxy/plugins/config.py`

- Added `theme_accent_numix` to the `Accent` list
- Added `theme_dirty_accent_numix` to the `Tab Misc` list

##### Additions to: `st-boxy/plugins/presets.py`

- Added `theme_accent_numix` to the `OPTIONS` list
- Added `theme_dirty_accent_numix` to the `OPTIONS` list
    - Note: The `theme_dirty_accent_*` items are not sorted alphabetically although the `theme_accent_*` items are
- Added `Numix` preset settings to the `PRESETS` ordered dictionary
    - See **Numix Preset** section below

##### Additions to: `st-boxy/Preferences.sublime-settings`

- Added `"theme_accent_numix": false,` to section `2.3 Accent`
- Added `"theme_dirty_accent_numix": false,` to section `4.4 Tab Misc`

Committed the changes with the message: `feat: add numix accent and numix preset`

Pushed the `numix` branch to GitHub: `mattst/st-boxy`

Issued the pull request on GitHub.

#### How Has This Been Tested?

The Numix accent has been tested and is working with:

- The 4 `.sublime-theme` files and their corresponding color scheme `.tmTheme` files
- All the settings from `st-boxy/Preferences.sublime-settings` were each tested in turn
- Setting the accent using the command: `Boxy Theme: Configuration --> Global --> Accent`
- Setting the dirty accent using the command: `Boxy Theme: Configuration --> Tabs --> Tab Misc`
- Setting the Numix preset using the command: `Boxy Theme: Presets --> Numix`

#### Numix Preset

[As I mentioned](https://github.com/oivva/st-boxy/issues/126) the Numix colour is already used as the principal colour of 4 Sublime Text themes available on Package Control. All the other Boxy presets mimic the style and colour of 1 specific theme, but there are 4 Numix themes which are all different - this made the decisions about which settings to use quite difficult. I tried to use the best aspects of all of them but that's subjective so the Numix preset basically consists of the settings which I think look best. Of course the lovely thing about Boxy is that the user can change anything they like to fit their taste.

##### Image File Creation

I wrote a `Bash` script to create new images from the contents of a folder and ran it to create the 4 accent colour folders: `buttons`, `scrollbars`, `sidebar`, and `tabs`.

The script used the `orange` accent images as the source images, changing the `orange` colour to the `numix` colour using the [Imagemagick](http://www.imagemagick.org/script/index.php) `convert` utility, with the following command:

```
# The '-fill' colour is the numix colour, the '-opaque' colour is the orange colour of the source
# files to be replaced.

# The use of '-alpha off' and '-alpha on' makes sure that all opacity in the images is preserved.

convert "$in_file" -alpha off -fill "#D64937" -opaque "#F2683E" -alpha on png32:"$out_file"
```

The script was also run to change the 'folder shadow effect' colour of the 3x `folder_atomized_expanded` and 3x `folder_dup_atomized_expanded` PNG images, with the following command:

```
# The '-fill' colour is the numix 'folder shadow effect' colour, the '-opaque' colour is the orange
# 'folder shadow effect' colour of the source files to be replaced.

convert "$in_file" -alpha off -fill "#A93223" -opaque "#C25332" -alpha on png32:"$out_file"
```

###### 1. File size is larger than the other accents

The pre-existing 9 accents all have an approx. total file size of 63,000 bytes, but the total size of the numix accent colour image files is almost double that at 124,928 bytes. Since I did not specify a compression level in the `convert` command the default level of 7 would have been used. [oivva wrote](https://github.com/oivva/st-boxy/issues/126#issuecomment-248513612) that he could optimize the files - but I can re-do the images with a specific PNG compression level if required.

###### 2. Problem with the image files which have lots of colours

The following 18 files in the `st-boxy/assets/accents/numix/sidebar/` folder each use lots of colours for curve edging, arrows, and arrow edging:

```
folder_atomized_expanded.png
folder_atomized_expanded@2x.png
folder_atomized_expanded@3x.png
folder_dup.png
folder_dup@2x.png
folder_dup@3x.png
folder_dup_atomized.png
folder_dup_atomized@2x.png
folder_dup_atomized@3x.png
folder_dup_atomized_expanded.png
folder_dup_atomized_expanded@2x.png
folder_dup_atomized_expanded@3x.png
folder_dup_expanded.png
folder_dup_expanded@2x.png
folder_dup_expanded@3x.png
folder_dup_materialized.png
folder_dup_materialized@2x.png
folder_dup_materialized@3x.png
```

I do NOT have the knowledge or skills to modify these 18 files properly.

All I have done to them is to change their standard orange colour to the numix colour, and to change the 'folder shadow effect' colour of the 3x `folder_atomized_expanded` and 3x `folder_dup_atomized_expanded` images (the shadow effect colour looks okay but could probably be better).

My apologies but any further work that needs to be done on these files will need to be done by someone else. I simply do not know how to do the curve and arrow edging.

However, the orange colour and the numix colour are similar enough for these images to look all right as they are, with the original orange accent edging and the untouched arrows, mainly because the images are quite small. Perhaps oivva could spare the time to make them better?

#### Finally

I hope everyone likes the new numix accent. :)

Closes #126

### CODE REVIEW

**Comment by oivva** [comment]
Ah, @mattst, thank you a lot! 

Can you remove dist theme files (*.sublime-theme) from your commit? I will build them from my side.

Then I will:

* merge your pull request soon
* modify files `st-boxy/assets/accents/numix/sidebar/` from my side (I previously used [psd assets](https://github.com/oivva/st-boxy-assets/tree/master/design) with Photoshop scripts for generating the icons)
* optimize all assets

**Comment by mattst** [comment]
> Ah, @mattst, thank you a lot!

No problem, my pleasure.

> Can you remove dist theme files (*.sublime-theme) from your commit? I will build them from my side.

No problem, it is done.

> merge your pull request soon

Cool. :)

> modify files st-boxy/assets/accents/numix/sidebar/ from my side (I previously used psd assets with Photoshop scripts for generating the icons)

Since you already have the scripts written, maybe it would be best for you to recreate all the images from scratch using the Numix colour, whatever you think best?!

Cheers, mattst

**Comment by oivva** [comment]
Ok, it will be merged today. However I'll remove `theme_font_md` option from the `Numix` preset, because of [this](https://github.com/SublimeTextIssues/Core/issues/694) issue, users can change it manually.

**Comment by mattst** [comment]
@oivva Thanks.

By the way the icons look great.

I've done a bit more work and have some new options for Boxy. I'll have to make some changes now that you have changed the directory structure but should have another pull request for you in a day or two.

**Comment by oivva** [comment]
@mattst Ok, thanks 😉

**Comment by oivva** [comment]
@mattst 3.6.0 will be released today. So wait a little bit and Boxy will be stable again :wink: I have no plans for any breaking changes, just some enhancements and bug fixes.

**Pull request merged**
