### PR TITLE
feat: add settings to change the minimap viewport opacity

### PR DESCRIPTION
**Pull request by mattst**
#### Description

I have added 6 new settings which allow the opacity level of the minimap viewport to be changed. They work when the `always_show_minimap_viewport` setting is set to both `true` and `false`. The new settings are:

```
theme_minimap_viewport_opacity_xlw  -  extra low         -  viewport_opacity: 0.2
theme_minimap_viewport_opacity_lw   -  low               -  viewport_opacity: 0.4 (default)
theme_minimap_viewport_opacity_md   -  medium            -  viewport_opacity: 0.6
theme_minimap_viewport_opacity_hg   -  high              -  viewport_opacity: 0.8
theme_minimap_viewport_opacity_xh   -  extra high        -  viewport_opacity: 1.0
theme_minimap_viewport_opacity_xxh  -  extra extra high  -  viewport_opacity: 1.2
```

The `_xlw`, `_lw`, `_md`, `_hg`, `_xh`, and `_xxh` suffixes are based on the suffixes used in the saturation level of the sidebar icons settings, e.g. `theme_sidebar_icon_saturation_lw`, and the `_xxs` and `_xxl` suffixes used in the tab and panel sizes. I decided to use `_xlw` for extra low instead of `_xl` as that usually stands for extra large.

Note: I tried and decided against adding a 0.1 level because it can hardly be seen.

#### Motivation and Context

These settings add to the highly customizable nature of Boxy.

#### Additions Summary

- Added a minimap options file: `sources/themes/options/minimap.json`
  - The JSON in this file sets the `viewport_opacity` for the new settings
  - Both minimap viewport 'always visible' and 'visible on hover' are handled
- Added a line to include `options/minimap.json` in the `Minimap` section of the `sources/themes/*.json` files
- Added a `Minimap` section containing the new settings to: `Preferences.sublime-settings`
- Added a `Minimap` entry to the `SECTION_OPTIONS` ordered dictionary in: `plugins/config.py`
- Ran the `gulp build:themes` command to build the 6 dist .sublime-theme files
  - I removed the 6 dist .sublime-theme files before comitting (as per [your previous request](https://github.com/oivva/st-boxy/pull/132#issuecomment-250459584))

I should mention that the new settings only change the `viewport_opacity` value, e.g.

```
{
  "class": "minimap_control",
  "settings": ["always_show_minimap_viewport", "theme_minimap_viewport_opacity_md"],
  "viewport_opacity": 0.6
},
```

The 4th RGB values of the `viewport_color` all remain UNCHANGED at 75, as below. I played around with changing the 4th RGB value in conjunction with changing the `viewport_opacity` values but the new settings work perfectly well without changing the values from 75, so I left them alone.

```
{
  "class": "minimap_control",
  "settings": ["!theme_accent_mono", "theme_accent_orange"],
  "viewport_color": [242, 104, 62, 75]
}
```

#### How Has This Been Tested?

- Tested all the new settings with `always_show_minimap_viewport` set to both `true` and `false`
- Tested setting and unsetting them all using the command: `Boxy Theme: Configuration --> Minimap`

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.

#### Finally

In my last pull request [you asked me to](https://github.com/oivva/st-boxy/pull/132#issuecomment-250459584) "remove the dist theme files (*.sublime-theme)" from my commit because you wanted to build them on your side. I assumed that you would want to do that again so I removed them before committing.

Let me know if you like these new settings, I hope you do.

You have designed Boxy extremely well - it's really very easy to add features once you see how it all fits together. Well done. :)

### CODE REVIEW

**Comment by oivva** [comment]
Thanks :wink: I'll merge it just a little bit later.

**Comment by oivva** [comment]
Looks good :sunglasses: Thanks again :wink:

**Comment by mattst** [comment]
No problem.

I just tested the `theme_minimap_viewport_opacity_*` settings and setting and unsetting them using the `Boxy Theme: Configuration --> Minimap` command with the latest `dev` build (commit: `556e5f6b`) and it all works perfectly on my system (Linux).

Also I checked the Boxy *Package Control* stats. 5,004 installs this month alone (not including today). I think Boxy has the potential to become the most installed theme. I think it's streets ahead of any other. :)

**Comment by mattst** [comment]
I also thought about adding settings to change the opacity of the minimap itself. I had a look through the ST `Default.sublime-theme` and could not find any way of doing this so I suspect it is not possible at the moment. Do you know of any way to do that?

**Comment by oivva** [comment]
> Do you know of any way to do that?

I think it's impossible at all. So we have what we have 😄

**Pull request merged**
